# Generated by Django 5.1.2 on 2024-10-15 07:29

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Pant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('productType', models.CharField(default='Pant', max_length=20)),
                ('category', models.CharField(max_length=100)),
                ('ref', models.CharField(max_length=100)),
                ('name', models.CharField(max_length=100)),
                ('price', models.FloatField(validators=[django.core.validators.MinValueValidator(0.0)])),
                ('newest', models.BooleanField(default=False)),
                ('promo', models.FloatField(default=0, validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(100.0)])),
                ('image', models.ImageField(upload_to='Shirts/')),
            ],
        ),
        migrations.CreateModel(
            name='Sandal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('productType', models.CharField(default='Sandal', max_length=20)),
                ('category', models.CharField(max_length=100)),
                ('ref', models.CharField(max_length=100)),
                ('name', models.CharField(max_length=100)),
                ('price', models.FloatField(validators=[django.core.validators.MinValueValidator(0.0)])),
                ('newest', models.BooleanField(default=False)),
                ('promo', models.FloatField(default=0, validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(100.0)])),
                ('image', models.ImageField(upload_to='sandals/')),
            ],
        ),
        migrations.CreateModel(
            name='Shirt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('productType', models.CharField(default='Shirt', max_length=20)),
                ('category', models.CharField(max_length=100)),
                ('ref', models.CharField(max_length=100)),
                ('name', models.CharField(max_length=100)),
                ('price', models.FloatField(validators=[django.core.validators.MinValueValidator(0.0)])),
                ('newest', models.BooleanField(default=False)),
                ('promo', models.FloatField(default=0, validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(100.0)])),
                ('image', models.ImageField(upload_to='Shirts/')),
            ],
        ),
        migrations.CreateModel(
            name='Shoe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('productType', models.CharField(default='Shoe', max_length=20)),
                ('category', models.CharField(max_length=100)),
                ('ref', models.CharField(max_length=100)),
                ('name', models.CharField(max_length=100)),
                ('price', models.FloatField(validators=[django.core.validators.MinValueValidator(0.0)])),
                ('newest', models.BooleanField(default=False)),
                ('promo', models.FloatField(default=0, validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(100.0)])),
                ('image', models.ImageField(default='shoes/empty.jpg', upload_to='shoes/')),
                ('image1', models.ImageField(default='shoes/empty.jpg', upload_to='shoes/')),
                ('image2', models.ImageField(default='shoes/empty.jpg', upload_to='shoes/')),
                ('image3', models.ImageField(default='shoes/empty.jpg', upload_to='shoes/')),
                ('image4', models.ImageField(default='shoes/empty.jpg', upload_to='shoes/')),
            ],
        ),
        migrations.CreateModel(
            name='PantDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('size', models.PositiveIntegerField()),
                ('quantity', models.PositiveIntegerField()),
                ('productId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='store.pant')),
            ],
        ),
        migrations.CreateModel(
            name='SandalDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('size', models.PositiveIntegerField()),
                ('quantity', models.PositiveIntegerField()),
                ('productId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='store.sandal')),
            ],
        ),
        migrations.CreateModel(
            name='ShirtDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('size', models.CharField(max_length=100)),
                ('quantity', models.PositiveIntegerField()),
                ('productId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='store.shirt')),
            ],
        ),
        migrations.CreateModel(
            name='ShoeDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('size', models.PositiveIntegerField()),
                ('quantity', models.PositiveIntegerField()),
                ('productId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='store.shoe')),
            ],
        ),
    ]
