# Generated by Django 5.1.2 on 2024-10-25 07:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0002_client_productordered'),
    ]

    operations = [
        migrations.AddField(
            model_name='productordered',
            name='product_id',
            field=models.PositiveIntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='client',
            name='phone',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='pant',
            name='productType',
            field=models.CharField(default='Pant', editable=False, max_length=20),
        ),
        migrations.AlterField(
            model_name='sandal',
            name='productType',
            field=models.CharField(default='Sandal', editable=False, max_length=20),
        ),
        migrations.AlterField(
            model_name='shirt',
            name='productType',
            field=models.CharField(default='Shirt', editable=False, max_length=20),
        ),
        migrations.AlterField(
            model_name='shoe',
            name='productType',
            field=models.CharField(default='Shoe', editable=False, max_length=20),
        ),
    ]
