# Generated by Django 5.1.2 on 2024-10-25 07:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0003_productordered_product_id_alter_client_phone_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ProductOrdered',
        ),
    ]
